services:
  productapi:
    build:
      context: .
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Mongo__ConnectionStrings: mongodb://product-service:product-service@customerdb:27017
      Mongo__Database: product-service
      Urls: http://+:5003
    command: bash start-dev.sh
    ports:
      - "5003:5003"
    networks:
      - awesome-shop-services-net
    volumes:
      - .:/AwesomeShop.Services.Products
    depends_on:
      - productdb
  productdb:
    image: mongodb/mongodb-community-server:7.0.5-ubi8
    environment:
      MONGO_INITDB_ROOT_USERNAME: product-service
      MONGO_INITDB_ROOT_PASSWORD: product-service
    ports:
      - "27020:27017"
    networks:
      - awesome-shop-services-net

networks:
  awesome-shop-services-net:
    name: awesome-shop-services-net
    external: true
